[build-system]
requires = ["setuptools", "torch", "pip"]
build-backend = "setuptools.build_meta"

[project]
name = "AnalysisTopGNN-Extensions"
version = "1.1"
readme = "README.md"
authors = [{name = "woywoy123"}]
