[build-system]
requires = ["pip", "setuptools", "wheel", "cython", "numpy"]
build-backend = "setuptools.build_meta"

[project]
name = "AnalysisG"
version = "3.0"
authors = [{name = "woywoy123"}]
readme = "README.md"
