[build-system]
requires = [
        "setuptools", 
        "wheel", 
        "cython",
        "numpy==1.23.5", 
        "pip"
]

build-backend = "setuptools.build_meta"

[project]
name = "AnalysisTopGNN"
version = "2.1"
readme = "README.md"
authors = [
        {name = "woywoy123"}, 
]
