# Very useful documentation: 
# https://github.com/ptheywood/cuda-cmake-github-actions/blob/master/.github/workflows/Ubuntu.yml

name: AnalysisTopGNN-Building-Action

on:
        push: 
                branches: ["CI-CD-testing-tom"]

jobs:
        build:
                runs-on: ubuntu-latest
                include:
                        - runs-on: ubuntu-latest
                          compiler: gcc
                          gcc: 11
                          cuda: "11.8"
                steps:
                        - uses: actions/checkout@v3
                        - uses: actions/setup-python@v4
                          with:
                                    python-version: '3.10'
                                    cache: 'pip'

                        - name: Building AnalysisTopGNN
                          run: pip install .

                        - name: Building Torch-Extensions-CPP
                          run: |
                                  export CC=gcc-11
                                  export CXX=g++-11
                                  sudo apt-get install -y gcc-11 g++-11
                                  cd torch-extensions 
                                  pip install .
                                  exit 0

                        - name: Building Torch-Extensions-CUDA
                          run: |
                                  export CC=gcc-11
                                  export CXX=g++-11
                                  sudo apt-get install -y ${CC} ${CXX}
                                  chmod +x ./.github/scripts/cuda_install.sh
                                  ./.github/scripts/cuda_install.sh
                                  export CUDA_PATH=/usr/local/cuda
                                  export CUDA_HOME=/usr/local/cuda
                                  cd torch-extensions
                                  pip install .
                                  exit 0
